### ISSUE TITLE
Country array does not reset after clicking 'restart'

### ISSUE THREAD

**Issue by hursittarcan** [breakbuddy/breakbuddy#1]
The `possibleCountry` array that stores the possible countries does `not refresh` after clicking `restart` at the end of the game. 
This bug causes previous `ok` countries to stay in the array, this bug leads to `misleading advising`.

**Comment by HursitTarcan** [comment]
Possible fix = `possibleCountries.length = 0`.

**Comment by hursittarcan** [comment]
> Possible fix = `possibleCountries.length = 0`.

Add to API code & Electron App (beta).
